#pragma once
#include "CoreMinimal.h"
#include "Types/AbxrDelegates.h"
#include "Types/AbxrTypes.h"

namespace Abxr
{
	ABXRLIB_API inline void Authenticate();
	
	ABXRLIB_API inline FAbxrAuthCompleted& OnAuthCompleted();
	
	// Fired when a new module target becomes active (LMS-driven sequencing)
	ABXRLIB_API inline FAbxrModuleTarget& OnModuleTarget();

	// Fired when module sequencing has completed
	ABXRLIB_API inline FAbxrAllModulesCompleted& OnAllModulesCompleted();
	
	ABXRLIB_API inline TArray<FAbxrModuleData> GetModuleList();
	
	ABXRLIB_API inline bool StartModuleAtIndex(const int ModuleIndex);
	
	ABXRLIB_API inline void LogDebug(const FString& Text, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void LogDebug(const FString& Text);
	
	ABXRLIB_API inline void LogInfo(const FString& Text, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void LogInfo(const FString& Text);
	
	ABXRLIB_API inline void LogWarn(const FString& Text, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void LogWarn(const FString& Text);
	
	ABXRLIB_API inline void LogError(const FString& Text, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void LogError(const FString& Text);
	
	ABXRLIB_API inline void LogCritical(const FString& Text, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void LogCritical(const FString& Text);
	
	ABXRLIB_API inline void Log(const FString& Text, const ELogLevel Level, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void Log(const FString& Text, const ELogLevel Level);
	ABXRLIB_API inline void Log(const FString& Text);
	
	ABXRLIB_API inline void Event(const FString& Name, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void Event(const FString& Name);
	ABXRLIB_API inline void Event(const FString& Name, const FVector& Position, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void Event(const FString& Name, const FVector& Position);
	
	ABXRLIB_API inline void Telemetry(const FString& Name, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void Telemetry(const FString& Name);
	
	ABXRLIB_API inline void EventAssessmentStart(const FString& AssessmentName, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventAssessmentStart(const FString& AssessmentName);
	
	ABXRLIB_API inline void EventAssessmentComplete(const FString& AssessmentName, const int Score, const EEventStatus Status, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventAssessmentComplete(const FString& AssessmentName, const int Score, const EEventStatus Status);
	
	ABXRLIB_API inline void EventObjectiveStart(const FString& ObjectiveName, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventObjectiveStart(const FString& ObjectiveName);
	
	ABXRLIB_API inline void EventObjectiveComplete(const FString& ObjectiveName, const int Score, const EEventStatus Status, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventObjectiveComplete(const FString& ObjectiveName, const int Score, const EEventStatus Status);
	
	ABXRLIB_API inline void EventInteractionStart(const FString& InteractionName, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventInteractionStart(const FString& InteractionName);
	
	ABXRLIB_API inline void EventInteractionComplete(const FString& InteractionName, const EInteractionType InteractionType, const FString& Response, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventInteractionComplete(const FString& InteractionName, const EInteractionType InteractionType, const FString& Response);
	
	ABXRLIB_API inline void EventLevelStart(const FString& LevelName, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventLevelStart(const FString& LevelName);
	
	ABXRLIB_API inline void EventLevelComplete(const FString& LevelName, const int Score, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventLevelComplete(const FString& LevelName, const int Score);
	
	ABXRLIB_API inline void EventCritical(const FString& Label, TMap<FString, FString>& Meta);
	ABXRLIB_API inline void EventCritical(const FString& Label);
	
	// Gets the UUID assigned to device by ArborXR
	ABXRLIB_API inline FString GetDeviceId();

	// Gets the serial number assigned to device by OEM
	ABXRLIB_API inline FString GetDeviceSerial();

	// Gets the title given to device by admin through the ArborXR Web Portal
	ABXRLIB_API inline FString GetDeviceTitle();

	// Gets the tags added to device by admin through the ArborXR Web Portal
	ABXRLIB_API inline TArray<FString> GetDeviceTags();

	// Gets the UUID of the organization where the device is assigned. Organizations are created in the ArborXR Web Portal
	ABXRLIB_API inline FString GetOrgId();

	// Gets the name assigned to organization by admin through the ArborXR Web Portal
	ABXRLIB_API inline FString GetOrgTitle();

	// Gets the identifier generated by ArborXR when admin assigns title to organization
	ABXRLIB_API inline FString GetOrgSlug();

	// Gets the physical MAC address assigned to device by OEM
	ABXRLIB_API inline FString GetMacAddressFixed();

	// Gets the randomized MAC address for the current WiFi connection
	ABXRLIB_API inline FString GetMacAddressRandom();

	// Gets whether the device is SSO authenticated
	ABXRLIB_API inline bool GetIsAuthenticated();

	// Gets SSO access token
	ABXRLIB_API inline FString GetAccessToken();

	// Gets SSO refresh token
	ABXRLIB_API inline FString GetRefreshToken();

	// Gets SSO token remaining lifetime
	ABXRLIB_API inline FDateTime GetExpiresDateUtc();

	// Gets the device fingerprint
	ABXRLIB_API inline FString GetFingerprint();
	
	// Start a new session with a fresh session identifier
	// Generates a new session ID and performs fresh authentication
	// Useful for starting new training experiences or resetting user context
	ABXRLIB_API inline void StartNewSession();

	// Get the learner/user data from the most recent authentication completion
	// This is the userData object from the authentication response, containing user preferences and information
	// Returns an empty map if no authentication has completed yet
	ABXRLIB_API inline TMap<FString, FString> GetUserData();

	// Register a super metadata that will be automatically included in all events
	// super metadata persist across app sessions and are stored locally
	ABXRLIB_API inline void Register(const FString& Key, const FString& Value);

	// Register a super metadata only if it doesn't already exist
	// Will not overwrite existing super metadata with the same key
	ABXRLIB_API inline void RegisterOnce(const FString& Key, const FString& Value);
	
	// Remove a super metadata entry
	ABXRLIB_API inline void Unregister(const FString& Key);

	// Clear all super metadata
	// Clears all super metadata from persistent storage
	ABXRLIB_API inline void Reset();

	// Get a copy of all current super metadata
	ABXRLIB_API inline TMap<FString, FString> GetSuperMetaData();

	ABXRLIB_API inline void LoadSuperMetaData();
}
